#ifndef _PLAN4_LQR_SPEED_PLANNING_H_
#define _PLAN4_LQR_SPEED_PLANNING_H_

/*
 * Plan4 continuous route tracking.
 *
 * The route table is generated by generate_plan4_smooth_path.py.  Each
 * sample contains a tangent (target_yaw_deg), a curvature and an offline
 * feasible speed.  Ordinary samples are pass-through samples: they never
 * create a zero-speed barrier.
 */

#define NAV_REPLAY_USE_STATIC_ROUTE_TABLE           1

/* Local segment projection and preview.  The generated route is nominally
 * 50 mm/sample, therefore 120 points cover roughly six metres. */
#define PLAN4_LQR_SEARCH_RANGE_POINTS               120U
#define PLAN4_LQR_RECOVER_SEARCH_RANGE_POINTS       300U
#define PLAN4_LQR_MAX_TRACK_DIST_MM                 900.0f
#define PLAN4_LQR_PROJECTION_MIN_SEG_MM             1.0f
#define PLAN4_LQR_PREVIEW_POINTS                    5U
#define PLAN4_LQR_SHARP_CURVATURE_TH                0.0015f
#define PLAN4_LQR_SHARP_PREVIEW_POINTS              2U

/* u = Kff * v*kappa + Ky*ey + Kpsi*epsi.  Check PLAN4_LQR_SIGN first if the
 * real vehicle corrects in the opposite direction. */
#define PLAN4_LQR_SIGN                              1.0f
#define PLAN4_LQR_K_LATERAL                         0.030f
#define PLAN4_LQR_K_HEADING                         0.80f
#define PLAN4_LQR_K_YAW_RATE_FF                     8.0f
#define PLAN4_LQR_SPEED_TO_MM_S                     4.79f
#define PLAN4_LQR_ERR_LIMIT_LOW_DEG                 34.0f
#define PLAN4_LQR_ERR_LIMIT_HIGH_DEG                22.0f
#define PLAN4_LQR_ERR_SLEW_LOW_DEG                  16.0f
#define PLAN4_LQR_ERR_SLEW_HIGH_DEG                  8.0f
#define PLAN4_LQR_FILTER_ALPHA_LOW                  0.75f
#define PLAN4_LQR_FILTER_ALPHA_HIGH                 0.48f
#define PLAN4_LQR_LOW_SPEED_MM_S                   500.0f
#define PLAN4_LQR_HIGH_SPEED_MM_S                 2500.0f
#define PLAN4_LQR_LATERAL_ERR_LIMIT_MM             650.0f

/* Runtime speed envelope.  It only limits the offline speed plan and always
 * retains a non-zero command while normal path tracking is active. */
#define PLAN4_TRACK_MIN_SPEED_CMD                  (-100.0f)
#define PLAN4_TRACK_CROSS_TRACK_SOFT_MM             250.0f
#define PLAN4_TRACK_CROSS_TRACK_HARD_MM             650.0f
#define PLAN4_TRACK_YAW_SOFT_DEG                     35.0f
#define PLAN4_TRACK_YAW_HARD_DEG                     80.0f
#define PLAN4_SPEED_ACCEL_STEP                       35.0f
#define PLAN4_SPEED_DECEL_STEP                      110.0f

/* Start a visual task while travelling through the generated 500 mm straight
 * approach corridor.  The navigation controller never stops at its marker. */
#define PLAN4_SPECIAL_HANDOFF_LEAD_MM               500.0f
#define PLAN4_SPECIAL_HANDOFF_TICKS                  10U
#define PLAN4_SPECIAL_HANDOFF_SPEED_STEP             40.0f
#define PLAN4_SPECIAL_HANDOFF_ERR_STEP_DEG            1.0f

#define PLAN4_START_HEADING_TOLERANCE_DEG             0.3f
#define PLAN4_START_HEADING_ERR_LIMIT_DEG             2.0f

extern volatile float target_speed_set;
extern volatile float err_degree;
extern volatile float roll_degree;

extern NavReplayState_e g_replay_state;
extern uint16 g_target_idx;
extern uint8 g_current_point_type;
extern uint8 g_special_action_trigger;
extern volatile uint8 entry_beep_request;
extern volatile uint8 exit_beep_request;

void NavReplay_Start(void);
void NavReplay_Stop(void);
void NavReplay_Process(void);
uint16 NavReplay_LoadStaticRouteToRam(void);

#endif
