#ifndef __WIFI_OPTIONS_H__
#define __WIFI_OPTIONS_H__

#include "sys_options.h"

#define WIFI_CORE_0 0
#define WIFI_CORE_1 1
#define WIFI_PROTOCOL_ASSISTANT 1
#define WIFI_PROTOCOL_CUSTOM 2

#if (WIFI_USE && (WIFI_CORE_SELECT != WIFI_CORE_0) && (WIFI_CORE_SELECT != WIFI_CORE_1))
#error "WIFI config error: invalid WIFI_CORE_SELECT."
#endif

#if (WIFI_USE && (WIFI_PROTOCOL_SELECT != WIFI_PROTOCOL_ASSISTANT) && (WIFI_PROTOCOL_SELECT != WIFI_PROTOCOL_CUSTOM))
#error "WIFI config error: invalid WIFI_PROTOCOL_SELECT."
#endif

// 0核 + 逐飞助手：只做数据传输；1核 + 逐飞助手：只做图像传输。
// 0核 + 自定义协议：惯导/GPS上位机；1核 + 自定义协议：视觉图像上位机。
#define WIFI_CORE0_USE              (WIFI_USE && (WIFI_CORE_SELECT == WIFI_CORE_0))
#define WIFI_CORE1_USE              (WIFI_USE && (WIFI_CORE_SELECT == WIFI_CORE_1))
#define WIFI_CORE0_ASSISTANT        (WIFI_CORE0_USE && (WIFI_PROTOCOL_SELECT == WIFI_PROTOCOL_ASSISTANT))
#define WIFI_CORE1_ASSISTANT        (WIFI_CORE1_USE && (WIFI_PROTOCOL_SELECT == WIFI_PROTOCOL_ASSISTANT))
#define WIFI_CORE0_CUSTOM_PROTOCOL  (WIFI_CORE0_USE && (WIFI_PROTOCOL_SELECT == WIFI_PROTOCOL_CUSTOM))
#define WIFI_CORE1_CUSTOM_IMAGE     (WIFI_CORE1_USE && (WIFI_PROTOCOL_SELECT == WIFI_PROTOCOL_CUSTOM))

// 兼容旧代码命名。
#define WIFI_CAMERA_AND_ASSISTANT   WIFI_CORE0_ASSISTANT
#define WIFI_IMAGE_SEND             0

#endif // __WIFI_OPTIONS_H__
