#ifndef _NAV_REPLAY_ROUTE_TABLE_H_
#define _NAV_REPLAY_ROUTE_TABLE_H_

#include "nav_ram.h"

// Auto-generated by tools/webview_nav_marker/csv_to_nav_table.py
// Source CSV: E:/github_projects/autocar1/environment4BB7/Seekfree_CYT4BB_Opensource_Library/project2/tools/webview_nav_marker科目三/nav_mark_points_20260724_233115.csv
// Generated at: 2026-07-24 23:31:44

#define NAV_REPLAY_START_HEADING_VALID 0
#define NAV_REPLAY_START_HEADING_DEG 135.787f

#define NAV_REPLAY_STATIC_ROUTE_COUNT 3

static const NavRamPoint_t nav_replay_static_route_points[3] = {
    {-6250.392f, -1995.105f, -2.612f, 142.448f, (uint8)5},
    {-7352.737f, -1807.333f, -6.850f, 139.508f, (uint8)50},
    {-9052.034f, -106.020f, -31.716f, 125.130f, (uint8)0},
};

#endif // _NAV_REPLAY_ROUTE_TABLE_H_
