#ifndef _NAV_REPLAY_ROUTE_TABLE_H_
#define _NAV_REPLAY_ROUTE_TABLE_H_

#include "nav_ram.h"

// Auto-generated by tools/webview_nav_marker/spline_interpolate.py
// Generated at: 2026-04-05 00:34:28
// Interpolation Method: Cubic Spline (三次样条)
// Interpolation interval: ~20.0mm
// Note: Origin (0,0) was used for curve shaping but excluded from this table.

#define NAV_REPLAY_START_HEADING_VALID 0
#define NAV_REPLAY_START_HEADING_DEG 0.0f

#define NAV_REPLAY_STATIC_ROUTE_COUNT 1

static const NavRamPoint_t nav_replay_static_route_points[1] = {
    {0.005f, 0.036f, (uint8)0},
};

#endif // _NAV_REPLAY_ROUTE_TABLE_H_
