#ifndef _NAV_REPLAY_ROUTE_TABLE_H_
#define _NAV_REPLAY_ROUTE_TABLE_H_

#include "nav_ram.h"

// Auto-generated by tools/webview_nav_marker/csv_to_nav_table.py
// Source CSV: E:/github_projects/autocar1/environment4BB7/Seekfree_CYT4BB_Opensource_Library/project2/tools/webview_nav_marker科目三/nav_mark_points_20260724_172737.csv
// Generated at: 2026-07-24 17:27:45

#define NAV_REPLAY_START_HEADING_VALID 0
#define NAV_REPLAY_START_HEADING_DEG 133.265f

#define NAV_REPLAY_STATIC_ROUTE_COUNT 3

static const NavRamPoint_t nav_replay_static_route_points[3] = {
    {-6021.182f, -1999.170f, -6.902f, 138.653f, (uint8)4},
    {-9399.015f, -1590.277f, -6.902f, 139.047f, (uint8)40},
    {-12092.488f, -63.306f, 0.000f, 125.509f, (uint8)0},
};

#endif // _NAV_REPLAY_ROUTE_TABLE_H_
