#!/usr/bin/env python3
"""Convert complementary-fusion marker CSV to a C route table header."""

from __future__ import annotations

import argparse
import datetime as dt
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
NAV_MARKER_DIR = SCRIPT_DIR.parent / "webview_nav_marker"
if str(NAV_MARKER_DIR) not in sys.path:
    sys.path.insert(0, str(NAV_MARKER_DIR))

import csv_to_nav_table as nav_csv

MAX_POINTS_DEFAULT = nav_csv.MAX_POINTS_DEFAULT


def load_manual_launch_heading(project_root: Path) -> float:
    sys_options_path = project_root / "code" / "config" / "sys_options.h"
    text = sys_options_path.read_text(encoding="utf-8")
    match = re.search(
        r"#define\s+CF_MANUAL_LAUNCH_HEADING_DEG\s+([+-]?(?:\d+(?:\.\d*)?|\.\d+))f?",
        text,
    )
    if not match:
        raise ValueError(f"CF_MANUAL_LAUNCH_HEADING_DEG not found in {sys_options_path}")
    return float(match.group(1))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Convert CF marker CSV to C header")
    parser.add_argument("csv", nargs="?", help="Path to exported CSV")
    parser.add_argument(
        "--output",
        help="Output header path (default: code/navigation/cf_nav_replay_route_table.h)",
    )
    parser.add_argument(
        "--max-points",
        type=int,
        default=MAX_POINTS_DEFAULT,
        help=f"Maximum route points to keep (default: {MAX_POINTS_DEFAULT})",
    )
    return parser.parse_args()


def auto_find_latest_csv(script_dir: Path) -> Path:
    candidates = sorted(
        script_dir.glob("cf_mark_points_*.csv"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    if not candidates:
        raise FileNotFoundError("No cf_mark_points_*.csv found. Please pass CSV path explicitly.")
    return candidates[0]


def format_header(points, src_path: Path, start_heading):
    now = dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    count = len(points)
    heading_valid = 0
    heading_deg = 0.0 if start_heading is None else start_heading

    lines = [
        "#ifndef _CF_NAV_REPLAY_ROUTE_TABLE_H_",
        "#define _CF_NAV_REPLAY_ROUTE_TABLE_H_",
        "",
        "#include \"nav_ram.h\"",
        "",
        "// Auto-generated by tools/webview_gps_marker/csv_to_cf_nav_table.py",
        f"// Source CSV: {src_path.as_posix()}",
        f"// Generated at: {now}",
        "",
        f"#define NAV_REPLAY_START_HEADING_VALID {heading_valid}",
        f"#define NAV_REPLAY_START_HEADING_DEG {heading_deg:.3f}f",
        "",
        f"#define NAV_REPLAY_STATIC_ROUTE_COUNT {count}",
        "",
    ]

    arr_size = count if count > 0 else 1
    lines.append(f"static const NavRamPoint_t nav_replay_static_route_points[{arr_size}] = {{")

    if count == 0:
        lines.append("    {0.0f, 0.0f, 0.0f, 0.0f, NAV_POINT_PATH},")
    else:
        for point in points:
            lines.append(
                "    "
                f"{{{point.x:.3f}f, {point.y:.3f}f, {point.target_yaw_deg:.3f}f, "
                f"{point.heading_deg:.3f}f, (uint8){point.point_type}}},"
            )

    lines.extend(
        [
            "};",
            "",
            "#endif // _CF_NAV_REPLAY_ROUTE_TABLE_H_",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    args = parse_args()

    project_root = SCRIPT_DIR.parent.parent
    csv_path = Path(args.csv).resolve() if args.csv else auto_find_latest_csv(SCRIPT_DIR)
    out_path = (
        Path(args.output).resolve()
        if args.output
        else (project_root / "code" / "navigation" / "cf_nav_replay_route_table.h")
    )

    if not csv_path.exists():
        raise FileNotFoundError(f"CSV not found: {csv_path}")
    if args.max_points <= 0:
        raise ValueError("--max-points must be > 0")

    points, _start_heading = nav_csv.read_points(csv_path)
    start_heading = load_manual_launch_heading(project_root)
    truncated = False
    if len(points) > args.max_points:
        points = points[: args.max_points]
        truncated = True

    out_text = format_header(points, csv_path, start_heading)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(out_text, encoding="utf-8")

    print(f"[OK] CSV: {csv_path}")
    print(f"[OK] Header generated: {out_path}")
    print(f"[OK] Route points: {len(points)}")
    if start_heading is None:
        print("[OK] Start heading: N/A")
    else:
        print(f"[OK] Start heading: {start_heading:.3f} deg")
    if truncated:
        print(f"[WARN] Truncated to max points: {args.max_points}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
