#!/usr/bin/env python3
"""Convert GPS marker CSV to pure GPS C route table header."""

from __future__ import annotations

import argparse
import csv
import datetime as dt
from pathlib import Path
from typing import List, Tuple

MAX_POINTS_DEFAULT = 5000


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Convert GPS marker CSV to C header")
    parser.add_argument("csv", nargs="?", help="Path to exported CSV")
    parser.add_argument(
        "--output",
        help="Output header path (default: code/navigation/gps_nav_replay_route_table.h)",
    )
    parser.add_argument(
        "--max-points",
        type=int,
        default=MAX_POINTS_DEFAULT,
        help=f"Maximum route points to keep (default: {MAX_POINTS_DEFAULT})",
    )
    return parser.parse_args()


def normalize_key(key: str) -> str:
    return key.strip().lower().replace(" ", "")


def auto_find_latest_csv(script_dir: Path) -> Path:
    candidates = sorted(
        script_dir.glob("gps_mark_points_*.csv"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    if not candidates:
        raise FileNotFoundError("No gps_mark_points_*.csv found. Please pass CSV path explicitly.")
    return candidates[0]


def read_points(csv_path: Path) -> List[Tuple[int, float, float, int]]:
    with csv_path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames is None:
            raise ValueError("CSV has no header")

        key_map = {normalize_key(k): k for k in reader.fieldnames if k is not None}
        required = ["x", "y", "point_type"]
        for k in required:
            if k not in key_map:
                raise ValueError(f"Missing required column: {k}")

        idx_col = key_map.get("index")
        x_col = key_map["x"]
        y_col = key_map["y"]
        t_col = key_map["point_type"]

        rows: List[Tuple[int, float, float, int]] = []
        for order, row in enumerate(reader):
            try:
                idx = int(row[idx_col]) if idx_col and row.get(idx_col, "") != "" else order
                x = float(row[x_col])
                y = float(row[y_col])
                point_type = int(float(row[t_col]))
                if point_type < 0:
                    point_type = 0
                if point_type > 5:
                    point_type = 5
                rows.append((idx, x, y, point_type))
            except Exception as exc:
                raise ValueError(f"Invalid row {order + 1}: {exc}") from exc

    rows.sort(key=lambda item: item[0])
    return rows


def format_header(points: List[Tuple[int, float, float, int]], src_path: Path) -> str:
    now = dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    count = len(points)

    lines = [
        "#ifndef _GPS_NAV_REPLAY_ROUTE_TABLE_H_",
        "#define _GPS_NAV_REPLAY_ROUTE_TABLE_H_",
        "",
        "#include \"nav_ram.h\"",
        "",
        "// Auto-generated by tools/webview_gps_marker/csv_to_gps_nav_table.py",
        f"// Source CSV: {src_path.as_posix()}",
        f"// Generated at: {now}",
        "",
        f"#define GPS_NAV_REPLAY_STATIC_ROUTE_COUNT {count}",
        "",
    ]

    arr_size = count if count > 0 else 1
    lines.append(f"static const NavRamPoint_t gps_nav_replay_static_route_points[{arr_size}] = {{")
    if count == 0:
        lines.append("    {0.0f, 0.0f, 0.0f, 0.0f, (uint8)0},")
    else:
        for _, x, y, point_type in points:
            lines.append(f"    {{{x:.3f}f, {y:.3f}f, 0.0f, 0.0f, (uint8){point_type}}},")
    lines.append("};")
    lines.append("")
    lines.append("#endif // _GPS_NAV_REPLAY_ROUTE_TABLE_H_")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    script_dir = Path(__file__).resolve().parent
    project_root = script_dir.parent.parent

    csv_path = Path(args.csv).resolve() if args.csv else auto_find_latest_csv(script_dir)
    out_path = Path(args.output).resolve() if args.output else (project_root / "code" / "navigation" / "gps_nav_replay_route_table.h")

    if not csv_path.exists():
        raise FileNotFoundError(f"CSV not found: {csv_path}")
    if args.max_points <= 0:
        raise ValueError("--max-points must be > 0")

    points = read_points(csv_path)
    truncated = False
    if len(points) > args.max_points:
        points = points[: args.max_points]
        truncated = True

    out_text = format_header(points, csv_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(out_text, encoding="utf-8")

    print(f"[OK] CSV: {csv_path}")
    print(f"[OK] Header generated: {out_path}")
    print(f"[OK] Route points: {len(points)}")
    if truncated:
        print(f"[WARN] Truncated to max points: {args.max_points}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
