"""Extract raw DIB AVI frames to PNG files.

The on-car videos generated by the SeekFree camera pipeline can be plain
uncompressed AVI/DIB streams. This script avoids an OpenCV/ffmpeg dependency
and saves each video frame as a PNG through Pillow.
"""

from __future__ import annotations

import argparse
import json
import struct
from dataclasses import dataclass
from pathlib import Path
from typing import BinaryIO, Iterator

from PIL import Image


DEFAULT_VIDEO = Path("data/2026_04_17_21_18_39_Video.avi")
DEFAULT_OUTPUT_ROOT = Path("tools/07_针对小车车载视频的cv算法/bridge/frames")


@dataclass(frozen=True)
class AviVideoInfo:
    width: int
    height: int
    bit_count: int
    compression: str
    total_frames_hint: int
    microseconds_per_frame: int


@dataclass(frozen=True)
class AviChunk:
    chunk_id: bytes
    size: int
    data_offset: int


def _read_exact(f: BinaryIO, size: int) -> bytes:
    data = f.read(size)
    if len(data) != size:
        raise EOFError(f"expected {size} bytes, got {len(data)}")
    return data


def _u32le(data: bytes, offset: int) -> int:
    return struct.unpack_from("<I", data, offset)[0]


def _i32le(data: bytes, offset: int) -> int:
    return struct.unpack_from("<i", data, offset)[0]


def read_video_info(path: Path) -> AviVideoInfo:
    data = path.read_bytes()

    if data[0:4] != b"RIFF" or data[8:12] != b"AVI ":
        raise ValueError(f"{path} is not a RIFF AVI file")

    avih_pos = data.find(b"avih")
    strf_pos = data.find(b"strf")
    if avih_pos < 0 or strf_pos < 0:
        raise ValueError("AVI header is missing avih/strf chunks")

    avih_size = _u32le(data, avih_pos + 4)
    avih = data[avih_pos + 8 : avih_pos + 8 + avih_size]
    microseconds_per_frame = _u32le(avih, 0)
    total_frames_hint = _u32le(avih, 16)
    width_from_avih = _u32le(avih, 32)
    height_from_avih = _u32le(avih, 36)

    strf_size = _u32le(data, strf_pos + 4)
    strf = data[strf_pos + 8 : strf_pos + 8 + strf_size]
    if len(strf) < 40:
        raise ValueError("AVI strf chunk is too short for BITMAPINFOHEADER")

    width = _i32le(strf, 4) or width_from_avih
    height = _i32le(strf, 8) or height_from_avih
    bit_count = struct.unpack_from("<H", strf, 14)[0]
    compression_u32 = _u32le(strf, 16)
    compression = (
        "DIB "
        if compression_u32 == 0
        else struct.pack("<I", compression_u32).decode("latin1", errors="replace")
    )

    return AviVideoInfo(
        width=abs(width),
        height=abs(height),
        bit_count=bit_count,
        compression=compression,
        total_frames_hint=total_frames_hint,
        microseconds_per_frame=microseconds_per_frame,
    )


def iter_avi_video_chunks(path: Path) -> Iterator[AviChunk]:
    with path.open("rb") as f:
        riff = _read_exact(f, 12)
        if riff[0:4] != b"RIFF" or riff[8:12] != b"AVI ":
            raise ValueError(f"{path} is not a RIFF AVI file")

        while True:
            header = f.read(8)
            if len(header) == 0:
                break
            if len(header) != 8:
                raise EOFError("truncated AVI chunk header")

            chunk_id = header[0:4]
            chunk_size = struct.unpack("<I", header[4:8])[0]
            data_offset = f.tell()

            if chunk_id == b"LIST":
                list_type = _read_exact(f, 4)
                list_payload_end = data_offset + chunk_size
                if list_type == b"movi":
                    while f.tell() + 8 <= list_payload_end:
                        sub_header = _read_exact(f, 8)
                        sub_id = sub_header[0:4]
                        sub_size = struct.unpack("<I", sub_header[4:8])[0]
                        sub_offset = f.tell()
                        if sub_id in (b"00db", b"00dc"):
                            yield AviChunk(sub_id, sub_size, sub_offset)
                        f.seek(sub_size + (sub_size & 1), 1)
                else:
                    f.seek(list_payload_end + (chunk_size & 1))
            else:
                f.seek(chunk_size + (chunk_size & 1), 1)


def dib_frame_to_image(frame: bytes, info: AviVideoInfo) -> Image.Image:
    if info.bit_count != 24:
        raise ValueError(f"only 24-bit DIB is supported, got {info.bit_count}-bit")
    if info.compression != "DIB ":
        raise ValueError(f"only uncompressed DIB is supported, got {info.compression!r}")

    stride = ((info.width * 3 + 3) // 4) * 4
    expected_size = stride * info.height
    if len(frame) < expected_size:
        raise ValueError(f"frame too short: {len(frame)} bytes, expected {expected_size}")

    # AVI DIB data is BGR and usually stored bottom-up.
    image = Image.frombytes(
        "RGB",
        (info.width, info.height),
        frame[:expected_size],
        "raw",
        "BGR",
        stride,
        -1,
    )
    return image


def extract_frames(
    video_path: Path,
    output_dir: Path,
    stride: int = 1,
    max_frames: int | None = None,
) -> dict:
    info = read_video_info(video_path)
    output_dir.mkdir(parents=True, exist_ok=True)

    saved = 0
    seen = 0

    with video_path.open("rb") as f:
        for chunk in iter_avi_video_chunks(video_path):
            seen += 1
            if (seen - 1) % stride != 0:
                continue

            f.seek(chunk.data_offset)
            frame = f.read(chunk.size)
            image = dib_frame_to_image(frame, info)
            saved += 1
            image.save(output_dir / f"frame_{seen:06d}.png")

            if max_frames is not None and saved >= max_frames:
                break

    metadata = {
        "video": str(video_path),
        "output_dir": str(output_dir),
        "width": info.width,
        "height": info.height,
        "bit_count": info.bit_count,
        "compression": info.compression,
        "total_frames_hint": info.total_frames_hint,
        "microseconds_per_frame": info.microseconds_per_frame,
        "fps_hint": 1000000.0 / info.microseconds_per_frame
        if info.microseconds_per_frame
        else None,
        "chunks_seen": seen,
        "frames_saved": saved,
        "stride": stride,
    }
    (output_dir / "metadata.json").write_text(
        json.dumps(metadata, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    return metadata


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Extract AVI/DIB video frames to PNG.")
    parser.add_argument("--video", type=Path, default=DEFAULT_VIDEO)
    parser.add_argument("--output", type=Path, default=None)
    parser.add_argument("--stride", type=int, default=1, help="save every Nth frame")
    parser.add_argument("--max-frames", type=int, default=None)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.stride < 1:
        raise ValueError("--stride must be >= 1")

    video_path = args.video
    output_dir = args.output
    if output_dir is None:
        output_dir = DEFAULT_OUTPUT_ROOT / video_path.stem

    metadata = extract_frames(video_path, output_dir, args.stride, args.max_frames)
    print(json.dumps(metadata, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
