#!/usr/bin/env python3
"""CSV/C 路表输出，以及路径和速度可视化渲染。"""
from __future__ import annotations

import csv
import math
from datetime import datetime
from pathlib import Path
from typing import Iterable, Optional

import matplotlib.pyplot as plt
import numpy as np

from .plan4_models import (
    ENTRY_TYPES,
    GENERATOR_SCRIPT_NAME,
    SPEED_TO_MM_S,
    TYPE_COLOR,
    TYPE_LABEL,
    Marker,
    PathSample,
)

def write_csv(output: Path, samples: list[PathSample], yaw: np.ndarray, curvature: np.ndarray, target_speed: np.ndarray) -> None:
    with output.open("w", encoding="utf-8", newline="") as csv_file:
        writer = csv.writer(csv_file)
        writer.writerow(["index", "x", "y", "target_yaw_deg", "heading", "point_type", "target_speed", "curvature", "forced_straight", "segment"])
        for index, (sample, sample_yaw, sample_curvature, speed) in enumerate(zip(samples, yaw, curvature, target_speed)):
            writer.writerow([index, f"{sample.x:.3f}", f"{sample.y:.3f}", f"{sample_yaw:.3f}", "0.000", sample.point_type, f"{speed:.3f}", f"{sample_curvature:.8f}", int(sample.forced_straight), sample.segment])


def write_c_header(output: Path, samples: list[PathSample], yaw: np.ndarray, curvature: np.ndarray, target_speed: np.ndarray, source: Path, start_heading: Optional[float]) -> None:
    # 获取当前的生成时间，格式为 年-月-日 时:分:秒
    generation_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        "#ifndef _NAV_REPLAY_ROUTE_TABLE_H_",
        "#define _NAV_REPLAY_ROUTE_TABLE_H_",
        "",
        "#include \"nav_ram.h\"",
        "",
        f"// Generated by {GENERATOR_SCRIPT_NAME} from {source.name}",
        f"// Generated at {generation_time}",
        "// Exit anchors 30/40/50 include the calibrated state-machine correction.",
        "#define NAV_REPLAY_START_HEADING_VALID 0",
        f"#define NAV_REPLAY_START_HEADING_DEG {0.0 if start_heading is None else start_heading:.3f}f",
        f"#define NAV_REPLAY_STATIC_ROUTE_COUNT {len(samples)}",
        "",
        f"static const NavRamPoint_t nav_replay_static_route_points[{len(samples)}] = {{",
    ]
    for sample, sample_yaw, sample_curvature, speed in zip(samples, yaw, curvature, target_speed):
        # NavRamPoint_t 字段顺序：x、y、目标航向、记录航向、点类型、目标速度、曲率。
        lines.append(f"    {{{sample.x:.3f}f, {sample.y:.3f}f, {sample_yaw:.3f}f, 0.0f, (uint8){sample.point_type}, {speed:.3f}f, {sample_curvature:.8f}f}},")
    lines.extend(["};", "", "#endif // _NAV_REPLAY_ROUTE_TABLE_H_", ""])
    output.write_text("\n".join(lines), encoding="utf-8")


def render(output: Path, markers: Iterable[Marker], samples: list[PathSample], s: np.ndarray, curvature: np.ndarray, target_speed: np.ndarray) -> None:
    plt.rcParams["font.sans-serif"] = ["Microsoft YaHei", "SimHei", "DejaVu Sans"]
    plt.rcParams["axes.unicode_minus"] = False
    points = np.array([(sample.x, sample.y) for sample in samples], dtype=float)
    marker_list = list(markers)
    # 箭头与标记点保持可见间隔，并根据地图尺度自适应长度。
    map_span_mm = max(float(np.ptp(points[:, 0])), float(np.ptp(points[:, 1])), 1.0)
    arrow_length_mm = min(1200.0, max(350.0, 0.035 * map_span_mm))
    forced = np.array([sample.forced_straight for sample in samples], dtype=bool)
    figure, (axis_path, axis_speed, axis_curve) = plt.subplots(1, 3, figsize=(20, 7), gridspec_kw={"width_ratios": [1.35, 1, 1]})
    axis_path.plot(points[:, 0], points[:, 1], color="#1d4ed8", linewidth=2.0, label="G2 平滑路径")
    if forced.any():
        axis_path.scatter(points[forced, 0], points[forced, 1], s=9, color="#f97316", label="强制直线段", zorder=3)
    for marker in marker_list:
        color = TYPE_COLOR[marker.point_type]
        axis_path.scatter(marker.x, marker.y, s=75, marker="o" if marker.point_type in (0, *ENTRY_TYPES) else "s", color=color, edgecolor="black", linewidth=0.6, zorder=5)
        # 普通路径点只保留位置标记，避免地图被大量文字遮挡。
        if marker.point_type != 0:
            axis_path.annotate(f"{marker.order}: {TYPE_LABEL[marker.point_type]}", (marker.x, marker.y), xytext=(5, 5), textcoords="offset points", fontsize=8)
        if marker.point_type in ENTRY_TYPES and marker.relative_yaw is not None:
            # 与 calc_path_yaw_deg() 相反变换：relative_yaw=0° 指向 X 负方向。
            yaw_rad = math.radians(marker.relative_yaw)
            direction = np.array([-math.cos(yaw_rad), -math.sin(yaw_rad)])
            arrow_start = np.array([marker.x, marker.y]) + 0.35 * arrow_length_mm * direction
            arrow_end = np.array([marker.x, marker.y]) + 1.35 * arrow_length_mm * direction
            axis_path.annotate(
                "",
                xy=arrow_end,
                xytext=arrow_start,
                arrowprops={"arrowstyle": "-|>", "color": color, "lw": 2.4, "mutation_scale": 18},
                zorder=6,
            )
            yaw_label = np.array([marker.x, marker.y]) + 1.55 * arrow_length_mm * direction
            axis_path.annotate(
                f"relative_yaw={marker.relative_yaw:.1f}°",
                yaw_label,
                ha="center",
                va="center",
                fontsize=8,
                fontweight="bold",
                color=color,
                zorder=6,
            )
    axis_path.set_title("Plan3 生成路径（橙色为入口前/出口后直线）")
    axis_path.set_xlabel("X (mm)")
    axis_path.set_ylabel("Y (mm)")
    axis_path.axis("equal")
    axis_path.grid(True, alpha=0.25)
    axis_path.legend(loc="best")

    axis_speed.plot(s, -target_speed * SPEED_TO_MM_S, color="#dc2626", linewidth=1.5)
    axis_speed.set_title("离线速度规划")
    axis_speed.set_xlabel("累计路径长度 (mm)")
    axis_speed.set_ylabel("目标速度 (mm/s)")
    axis_speed.grid(True, alpha=0.25)

    axis_curve.plot(s, curvature * 1000.0, color="#0f766e", linewidth=1.5)
    axis_curve.axhline(0.0, color="black", linewidth=0.8)
    axis_curve.set_title("路径曲率")
    axis_curve.set_xlabel("累计路径长度 (mm)")
    axis_curve.set_ylabel("曲率 (1/m)")
    axis_curve.grid(True, alpha=0.25)
    figure.suptitle(
        "请仔细检查地图（1.状态机的种类2.坡道前的打点需要拉一下）",
        fontsize=21,
        fontweight="bold",
    )
    figure.tight_layout(rect=(0, 0, 1, 0.92))
    figure.savefig(output, dpi=180)
    plt.show()
    plt.close(figure)


def render_speed_heatmap(output: Path, samples: list[PathSample], target_speed: np.ndarray) -> None:
    """单独绘制路径速度热力图，颜色表示物理目标速度。"""
    plt.rcParams["font.sans-serif"] = ["Microsoft YaHei", "SimHei", "DejaVu Sans"]
    plt.rcParams["axes.unicode_minus"] = False
    points = np.array([(sample.x, sample.y) for sample in samples], dtype=float)
    speed_mm_s = -target_speed * SPEED_TO_MM_S
    figure, axis = plt.subplots(figsize=(10, 8))
    heatmap = axis.scatter(
        points[:, 0],
        points[:, 1],
        c=speed_mm_s,
        cmap="turbo",
        s=18,
        linewidths=0.0,
    )
    axis.plot(points[:, 0], points[:, 1], color="#334155", linewidth=0.8, alpha=0.45, zorder=0)
    axis.set_title("Plan4 路径速度热力图")
    axis.set_xlabel("X (mm)")
    axis.set_ylabel("Y (mm)")
    axis.axis("equal")
    axis.grid(True, alpha=0.25)
    colorbar = figure.colorbar(heatmap, ax=axis, pad=0.02)
    colorbar.set_label("目标速度 (mm/s)")
    figure.tight_layout()
    figure.savefig(output, dpi=180)
    plt.show()
    plt.close(figure)


