import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import splprep, splev, PchipInterpolator, interp1d
import os
import re
from datetime import datetime

# 设置中文字体
plt.rcParams['font.sans-serif'] = ['SimHei']  # 用来正常显示中文标签
plt.rcParams['axes.unicode_minus'] = False    # 用来正常显示负号

INTERPOLATE_DIST = 20.0 # 目标插值间隔：20mm

def read_raw_points_from_header(file_path):
    points = []
    if not os.path.exists(file_path):
        print(f"找不到文件: {file_path}")
        return points
    
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # 查找数组内容
    match = re.search(r'static const NavRamPoint_t nav_replay_static_route_points\[.*?\] = \{(.*?)\};', content, re.DOTALL)
    if match:
        array_content = match.group(1)
        # 解析每一行的数据 {-1061.905f, 2385.714f, (uint8)0}
        pattern = r'\{\s*([+-]?[\d\.]+)f\s*,\s*([+-]?[\d\.]+)f\s*,\s*\(uint8\)(\d+)\s*\}'
        for m in re.finditer(pattern, array_content):
            x, y, t = float(m.group(1)), float(m.group(2)), int(m.group(3))
            points.append((x, y, t))
            
    return points

def generate_header(points, method_name, output_path):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("#ifndef _NAV_REPLAY_ROUTE_TABLE_H_\n")
        f.write("#define _NAV_REPLAY_ROUTE_TABLE_H_\n\n")
        f.write("#include \"nav_ram.h\"\n\n")
        f.write(f"// Auto-generated by tools/webview_nav_marker/spline_interpolate.py\n")
        f.write(f"// Generated at: {timestamp}\n")
        f.write(f"// Interpolation Method: {method_name}\n")
        f.write(f"// Interpolation interval: ~{INTERPOLATE_DIST}mm\n")
        f.write(f"// Note: Origin (0,0) was used for curve shaping but excluded from this table.\n\n")
        
        f.write("#define NAV_REPLAY_START_HEADING_VALID 0\n")
        f.write("#define NAV_REPLAY_START_HEADING_DEG 0.000f\n\n")
        
        f.write(f"#define NAV_REPLAY_STATIC_ROUTE_COUNT {len(points)}\n\n")
        
        f.write(f"static const NavRamPoint_t nav_replay_static_route_points[{len(points)}] = {{\n")
        for p in points:
            f.write(f"    {{{p[0]:.3f}f, {p[1]:.3f}f, (uint8){p[2]}}},\n")
        f.write("};\n\n")
        
        f.write("#endif // _NAV_REPLAY_ROUTE_TABLE_H_\n")

# 基于给定的高密度点，按照固定距离进行等距重采样
def resample_path(x_fine, y_fine, target_dist):
    # 计算精细点之间的累积距离
    diffs = np.sqrt(np.diff(x_fine)**2 + np.diff(y_fine)**2)
    cum_dist = np.insert(np.cumsum(diffs), 0, 0.0)
    total_length = cum_dist[-1]
    
    # 按照 target_dist 生成新的距离序列
    num_points = max(int(total_length / target_dist), 2)
    target_dists = np.linspace(0, total_length, num_points)
    
    # 对 x 和 y 分别关于累积距离做线性插值，得到近似严格等距的点
    x_new = np.interp(target_dists, cum_dist, x_fine)
    y_new = np.interp(target_dists, cum_dist, y_fine)
    
    return x_new, y_new, num_points

def main():
    header_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../code/navigation/nav_replay_route_table.h'))
    raw_points = read_raw_points_from_header(header_path)
    
    if not raw_points:
        print("未读取到任何原始数据点，程序退出。")
        return
        
    print(f"成功读取 {len(raw_points)} 个原始数据点。")

    # 引入 (0,0) 作为起点
    spline_input_points = [(0.0, 0.0, 0)] + raw_points
    x_orig = np.array([p[0] for p in spline_input_points])
    y_orig = np.array([p[1] for p in spline_input_points])
    
    # 计算原始点的累积弦长，用于参数化
    diffs = np.sqrt(np.diff(x_orig)**2 + np.diff(y_orig)**2)
    t_orig = np.insert(np.cumsum(diffs), 0, 0.0)
    t_orig /= t_orig[-1] # 归一化到 0~1
    
    methods = {}
    
    # ================= 1. Cubic Spline (三次样条) =================
    k_degree = min(3, len(x_orig) - 1)
    tck, _ = splprep([x_orig, y_orig], s=0, k=k_degree)
    u_fine = np.linspace(0, 1, 2000)
    x_spline, y_spline = splev(u_fine, tck)
    x_spline_res, y_spline_res, n1 = resample_path(x_spline, y_spline, INTERPOLATE_DIST)
    methods['1'] = ('Cubic Spline (三次样条)', x_spline_res, y_spline_res)

    # ================= 2. PCHIP (分段三次Hermite保形插值) =================
    fx_pchip = PchipInterpolator(t_orig, x_orig)
    fy_pchip = PchipInterpolator(t_orig, y_orig)
    x_pchip = fx_pchip(u_fine)
    y_pchip = fy_pchip(u_fine)
    x_pchip_res, y_pchip_res, n2 = resample_path(x_pchip, y_pchip, INTERPOLATE_DIST)
    methods['2'] = ('PCHIP (保形插值)', x_pchip_res, y_pchip_res)

    # ================= 3. Linear (线性插值) =================
    fx_linear = interp1d(t_orig, x_orig, kind='linear')
    fy_linear = interp1d(t_orig, y_orig, kind='linear')
    x_linear = fx_linear(u_fine)
    y_linear = fy_linear(u_fine)
    x_linear_res, y_linear_res, n3 = resample_path(x_linear, y_linear, INTERPOLATE_DIST)
    methods['3'] = ('Linear (线性直线)', x_linear_res, y_linear_res)

    # ================= 可视化展示 =================
    plt.ion() # 开启交互模式，不阻塞终端
    fig, axs = plt.subplots(1, 3, figsize=(15, 5))
    fig.canvas.manager.set_window_title('路径插值对比 (支持滚轮缩放放大)')
    
    for idx, (key, (name, x_res, y_res)) in enumerate(methods.items()):
        ax = axs[idx]
        ax.plot(x_orig, y_orig, 'ro-', label='原始点', markersize=6, zorder=3)
        ax.plot(x_res, y_res, 'b.-', markersize=3, label=f'重采样 (~20mm)', zorder=2)
        ax.plot(x_res[1] if len(x_res)>1 else x_res[0], y_res[1] if len(y_res)>1 else y_res[0], 'g*', markersize=10, label='起始点 (idx=1)', zorder=4)
        ax.set_title(f"[{key}] {name}")
        ax.set_xlabel('X (mm)')
        ax.set_ylabel('Y (mm)')
        ax.axis('equal')
        ax.grid(True)
        ax.legend()
    
    # 启用交互式缩放平移工具，方便查看局部细节
    plt.tight_layout()
    plt.pause(0.5)

    # ================= 终端交互 =================
    print("\n" + "="*50)
    print("请在弹出的图形窗口中观察三种插值效果：(可在窗口中使用放大镜工具查看细节)")
    print("  [1] Cubic Spline - 极其平滑，但急弯处可能出现过冲 (Overshoot)")
    print("  [2] PCHIP 保形   - 贴合原折线，不会过冲，弯道适中 (推荐)")
    print("  [3] Linear 直线  - 纯粹的多边形折线，拐角生硬")
    print("="*50)
    
    choice = input("👉 请输入您想采用的方法编号 (1/2/3) [默认 2]: ").strip()
    if choice not in methods:
        print("未输入或输入无效，默认选择 [2] PCHIP 保形插值")
        choice = '2'
        
    selected_name, sel_x, sel_y = methods[choice]
    
    # 组装点集，剔除第0个点(原点 0,0)
    final_points = []
    num_pts = len(sel_x)
    for i in range(1, num_pts):
        pt_type = raw_points[-1][2] if i == num_pts - 1 else 0
        final_points.append((sel_x[i], sel_y[i], pt_type))
        
    generate_header(final_points, selected_name, header_path)
    
    print(f"\n✅ 已选择: {selected_name}")
    print(f"✅ 头文件已生成覆盖: {header_path}")
    print(f"✅ 共 {num_pts} 个点，剔除原点后写入表中的有 {len(final_points)} 个点。")
    
    plt.ioff()
    print("\n您可以关闭图形窗口以结束程序...")
    plt.show()

if __name__ == "__main__":
    main()