import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import splprep, splev, PchipInterpolator, interp1d, Akima1DInterpolator
import os
import re
from datetime import datetime

# 设置中文字体
plt.rcParams['font.sans-serif'] = ['SimHei']  
plt.rcParams['axes.unicode_minus'] = False    

INTERPOLATE_DIST = 20.0 # 目标插值间隔：20mm

def read_raw_points_from_header(file_path):
    points = []
    if not os.path.exists(file_path):
        print(f"找不到文件: {file_path}")
        return points
    
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    match = re.search(r'static const NavRamPoint_t nav_replay_static_route_points\[.*?\] = \{(.*?)\};', content, re.DOTALL)
    if match:
        array_content = match.group(1)
        pattern = r'\{\s*([+-]?[\d\.]+)f\s*,\s*([+-]?[\d\.]+)f\s*,\s*\(uint8\)(\d+)\s*\}'
        for m in re.finditer(pattern, array_content):
            x, y, t = float(m.group(1)), float(m.group(2)), int(m.group(3))
            points.append((x, y, t))
    return points

def generate_header(points, method_name, output_path):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("#ifndef _NAV_REPLAY_ROUTE_TABLE_H_\n")
        f.write("#define _NAV_REPLAY_ROUTE_TABLE_H_\n\n")
        f.write("#include \"nav_ram.h\"\n\n")
        f.write(f"// Auto-generated by spline_interpolate.py\n")
        f.write(f"// Generated at: {timestamp}\n")
        f.write(f"// Interpolation Method: {method_name}\n")
        f.write(f"// Interpolation interval: ~{INTERPOLATE_DIST}mm\n")
        f.write(f"// Note: Origin (0,0) was used for curve shaping but excluded from this table.\n\n")
        
        f.write("#define NAV_REPLAY_START_HEADING_VALID 0\n")
        f.write("#define NAV_REPLAY_START_HEADING_DEG 0.000f\n\n")
        
        f.write(f"#define NAV_REPLAY_STATIC_ROUTE_COUNT {len(points)}\n\n")
        
        f.write(f"static const NavRamPoint_t nav_replay_static_route_points[{len(points)}] = {{\n")
        for p in points:
            f.write(f"    {{{p[0]:.3f}f, {p[1]:.3f}f, (uint8){p[2]}}},\n")
        f.write("};\n\n")
        
        f.write("#endif // _NAV_REPLAY_ROUTE_TABLE_H_\n")

# 等距重采样
def resample_path(x_fine, y_fine, target_dist):
    diffs = np.sqrt(np.diff(x_fine)**2 + np.diff(y_fine)**2)
    cum_dist = np.insert(np.cumsum(diffs), 0, 0.0)
    total_length = cum_dist[-1]
    
    if total_length == 0:
        return x_fine, y_fine, len(x_fine)
        
    num_points = max(int(total_length / target_dist), 2)
    target_dists = np.linspace(0, total_length, num_points)
    
    x_new = np.interp(target_dists, cum_dist, x_fine)
    y_new = np.interp(target_dists, cum_dist, y_fine)
    
    return x_new, y_new, num_points

# 拐角倒角平滑 (Corner Fillet / Blending)
def corner_fillet_path(x_orig, y_orig, fillet_radius=500.0):
    pts = np.vstack((x_orig, y_orig)).T
    new_pts = [pts[0]]
    
    for i in range(1, len(pts)-1):
        p0, p1, p2 = pts[i-1], pts[i], pts[i+1]
        
        # 计算线段向量和长度
        v1 = p0 - p1
        v2 = p2 - p1
        l1 = np.linalg.norm(v1)
        l2 = np.linalg.norm(v2)
        
        if l1 < 1e-3 or l2 < 1e-3:
            new_pts.append(p1)
            continue
            
        v1_norm = v1 / l1
        v2_norm = v2 / l2
        
        # 实际倒角截取长度 (不能超过线段的一半)
        cut_len = min(fillet_radius, l1 * 0.45, l2 * 0.45)
        
        # 倒角起点和终点
        p_start = p1 + v1_norm * cut_len
        p_end = p1 + v2_norm * cut_len
        
        # 使用二次贝塞尔曲线进行局部圆滑过渡
        t = np.linspace(0, 1, 20)
        bezier_x = (1-t)**2 * p_start[0] + 2*(1-t)*t * p1[0] + t**2 * p_end[0]
        bezier_y = (1-t)**2 * p_start[1] + 2*(1-t)*t * p1[1] + t**2 * p_end[1]
        
        new_pts.extend(np.vstack((bezier_x, bezier_y)).T)
        
    new_pts.append(pts[-1])
    new_pts = np.array(new_pts)
    return new_pts[:,0], new_pts[:,1]

# B样条平滑 (不严格过控制点)
def b_spline_path(x_orig, y_orig, smooth_factor=5.0):
    tck, u = splprep([x_orig, y_orig], s=smooth_factor, k=3)
    u_fine = np.linspace(0, 1, 2000)
    x_spline, y_spline = splev(u_fine, tck)
    return x_spline, y_spline

def main():
    header_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../code/navigation/nav_replay_route_table.h'))
    raw_points = read_raw_points_from_header(header_path)
    
    if not raw_points:
        print("未读取到任何原始数据点，程序退出。")
        return

    # 引入 (0,0) 作为起点
    spline_input_points = [(0.0, 0.0, 0)] + raw_points
    x_orig = np.array([p[0] for p in spline_input_points])
    y_orig = np.array([p[1] for p in spline_input_points])
    
    diffs = np.sqrt(np.diff(x_orig)**2 + np.diff(y_orig)**2)
    t_orig = np.insert(np.cumsum(diffs), 0, 0.0)
    t_orig /= t_orig[-1] 
    
    methods = {}
    u_fine = np.linspace(0, 1, 2000)
    
    # 1. Cubic Spline
    k_degree = min(3, len(x_orig) - 1)
    tck_cubic, _ = splprep([x_orig, y_orig], s=0, k=k_degree)
    x_c, y_c = splev(u_fine, tck_cubic)
    methods['1'] = ('Cubic Spline (严格过点,易过冲)', *resample_path(x_c, y_c, INTERPOLATE_DIST)[:2])

    # 2. PCHIP
    fx_pchip = PchipInterpolator(t_orig, x_orig)
    fy_pchip = PchipInterpolator(t_orig, y_orig)
    methods['2'] = ('PCHIP (严格过点,保形无过冲)', *resample_path(fx_pchip(u_fine), fy_pchip(u_fine), INTERPOLATE_DIST)[:2])

    # 3. Akima
    fx_akima = Akima1DInterpolator(t_orig, x_orig)
    fy_akima = Akima1DInterpolator(t_orig, y_orig)
    methods['3'] = ('Akima (严格过点,抑制过冲)', *resample_path(fx_akima(u_fine), fy_akima(u_fine), INTERPOLATE_DIST)[:2])

    # 4. Corner Fillet (几何倒角)
    # 取平均段距的 1/3 作为倒角半径尝试值
    avg_dist = np.mean(diffs)
    x_fillet, y_fillet = corner_fillet_path(x_orig, y_orig, fillet_radius=avg_dist*0.5)
    methods['4'] = ('Corner Fillet (直线+局部圆滑倒角)', *resample_path(x_fillet, y_fillet, INTERPOLATE_DIST)[:2])

    # 5. B-Spline Smoothing
    # s 越大越平滑，偏离控制点越远
    x_bs, y_bs = b_spline_path(x_orig, y_orig, smooth_factor=len(x_orig)*10)
    methods['5'] = ('B-Spline (控制点平滑,不严格过点)', *resample_path(x_bs, y_bs, INTERPOLATE_DIST)[:2])
    
    # 6. Linear 
    fx_lin = interp1d(t_orig, x_orig, kind='linear')
    fy_lin = interp1d(t_orig, y_orig, kind='linear')
    methods['6'] = ('Linear (纯粹直线)', *resample_path(fx_lin(u_fine), fy_lin(u_fine), INTERPOLATE_DIST)[:2])

    # ================= 可视化展示 =================
    plt.ion() 
    fig, axs = plt.subplots(2, 3, figsize=(16, 8))
    fig.canvas.manager.set_window_title('高级路径规划与插值对比')
    axs = axs.flatten()
    
    for idx, (key, (name, x_res, y_res)) in enumerate(methods.items()):
        ax = axs[idx]
        ax.plot(x_orig, y_orig, 'ro-', label='原始控制点', markersize=6, alpha=0.5, zorder=3)
        ax.plot(x_res, y_res, 'b.-', markersize=3, label='规划路线', zorder=2)
        if len(x_res) > 1:
            ax.plot(x_res[1], y_res[1], 'g*', markersize=10, label='起始点(剔除原点)', zorder=4)
        ax.set_title(f"[{key}] {name}")
        ax.axis('equal')
        ax.grid(True, linestyle='--', alpha=0.6)
        ax.legend()
        
    plt.tight_layout()
    plt.pause(0.5)

    # ================= 终端交互 =================
    print("\n" + "="*70)
    print(" 🚗 路径平滑与规划算法测试区")
    print("="*70)
    print(" [严格过点类]")
    print("  [1] Cubic Spline - 极其平滑连续，但急弯处易产生钟摆过冲 (Overshoot)。")
    print("  [2] PCHIP        - 物理保形插值，严格贴合折线包络，绝不过冲，弯道略生硬。")
    print("  [3] Akima        - 介于样条和保形之间，对阶跃点有极好的抑制效果。")
    print(" [非严格过点 / 几何平滑类 (更适合自动驾驶车道线生成)]")
    print("  [4] Corner Fillet- 保持长直道绝对直线，仅在拐角尖端做圆润过渡 (贴近人类驾驶习惯)。")
    print("  [5] B-Spline     - 将原点作为引力控制点，生成全局平滑流线，彻底消除突变曲率。")
    print(" [基础类]")
    print("  [6] Linear       - 纯粹的多边形折线连线，无任何平滑。")
    print("="*70)
    
    choice = input("👉 请输入您想采用的方法编号 (1~6) [默认 4]: ").strip()
    plt.close('all')
    
    if choice not in methods:
        print("未输入或输入无效，默认选择 [4] Corner Fillet 局部倒角")
        choice = '4'
        
    selected_name, sel_x, sel_y = methods[choice]
    
    final_points = []
    num_pts = len(sel_x)
    for i in range(1, num_pts):
        pt_type = raw_points[-1][2] if i == num_pts - 1 else 0
        final_points.append((sel_x[i], sel_y[i], pt_type))
        
    generate_header(final_points, selected_name, header_path)
    
    print(f"\n✅ 已选择: {selected_name}")
    print(f"✅ 头文件已生成覆盖: {header_path}")
    print(f"✅ 共产生 {num_pts} 个点，写入表中 {len(final_points)} 个点。")
    print("✅ 绘图窗口已自动关闭。")

if __name__ == "__main__":
    main()