#!/usr/bin/env python3
"""Convert exported nav marker CSV to a C route table header.

Input CSV columns (required): x, y, point_type
Optional: index (for ordering)

Default output:
    code/navigation/nav_replay_route_table.h
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import math
from pathlib import Path
from typing import List, Optional, Tuple

MAX_POINTS_DEFAULT = 166


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Convert nav marker CSV to C header")
    parser.add_argument("csv", nargs="?", help="Path to exported CSV")
    parser.add_argument(
        "--output",
        help="Output header path (default: code/navigation/nav_replay_route_table.h)",
    )
    parser.add_argument(
        "--max-points",
        type=int,
        default=MAX_POINTS_DEFAULT,
        help=f"Maximum route points to keep (default: {MAX_POINTS_DEFAULT})",
    )
    return parser.parse_args()


def normalize_key(key: str) -> str:
    return key.strip().lower().replace(" ", "")


def auto_find_latest_csv(script_dir: Path) -> Path:
    candidates = sorted(script_dir.glob("nav_mark_points_*.csv"), key=lambda p: p.stat().st_mtime, reverse=True)
    if not candidates:
        raise FileNotFoundError("No nav_mark_points_*.csv found. Please pass CSV path explicitly.")
    return candidates[0]


def normalize_heading_deg(value: float) -> Optional[float]:
    try:
        h = float(value)
    except (TypeError, ValueError):
        return None
    if not math.isfinite(h):
        return None
    h = math.fmod(h, 360.0)
    if h < 0.0:
        h += 360.0
    return h


def read_points(csv_path: Path) -> Tuple[List[Tuple[int, float, float, int]], Optional[float]]:
    with csv_path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames is None:
            raise ValueError("CSV has no header")

        key_map = {normalize_key(k): k for k in reader.fieldnames if k is not None}

        required = ["x", "y", "point_type"]
        for k in required:
            if k not in key_map:
                raise ValueError(f"Missing required column: {k}")

        idx_col = key_map.get("index")
        heading_col = key_map.get("start_heading")
        x_col = key_map["x"]
        y_col = key_map["y"]
        t_col = key_map["point_type"]

        rows: List[Tuple[int, float, float, int]] = []
        start_heading: Optional[float] = None
        for order, row in enumerate(reader):
            try:
                if heading_col and start_heading is None and row.get(heading_col, "").strip() != "":
                    parsed_heading = normalize_heading_deg(row[heading_col])
                    if parsed_heading is not None:
                        start_heading = parsed_heading

                idx = int(row[idx_col]) if idx_col and row.get(idx_col, "") != "" else order
                x = float(row[x_col])
                y = float(row[y_col])
                point_type = int(float(row[t_col]))
                if point_type < 0:
                    point_type = 0
                if point_type > 5:
                    point_type = 5
                rows.append((idx, x, y, point_type))
            except Exception as exc:
                raise ValueError(f"Invalid row {order + 1}: {exc}") from exc

        rows.sort(key=lambda r: r[0])
        return rows, start_heading


def format_header(points: List[Tuple[int, float, float, int]], src_path: Path, start_heading: Optional[float]) -> str:
    now = dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    count = len(points)
    heading_valid = 1 if start_heading is not None else 0
    heading_deg = 0.0 if start_heading is None else start_heading

    lines = [
        "#ifndef _NAV_REPLAY_ROUTE_TABLE_H_",
        "#define _NAV_REPLAY_ROUTE_TABLE_H_",
        "",
        "#include \"nav_ram.h\"",
        "",
        "// Auto-generated by tools/webview_nav_marker/csv_to_nav_table.py",
        f"// Source CSV: {src_path.as_posix()}",
        f"// Generated at: {now}",
        "",
        f"#define NAV_REPLAY_START_HEADING_VALID {heading_valid}",
        f"#define NAV_REPLAY_START_HEADING_DEG {heading_deg:.3f}f",
        "",
        f"#define NAV_REPLAY_STATIC_ROUTE_COUNT {count}",
        "",
    ]

    arr_size = count if count > 0 else 1
    lines.append(f"static const NavRamPoint_t nav_replay_static_route_points[{arr_size}] = {{")

    if count == 0:
        lines.append("    {0.0f, 0.0f, NAV_POINT_PATH}")
    else:
        for _, x, y, point_type in points:
            lines.append(f"    {{{x:.3f}f, {y:.3f}f, (uint8){point_type}}},")

    lines.append("};")
    lines.append("")
    lines.append("#endif // _NAV_REPLAY_ROUTE_TABLE_H_")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    args = parse_args()

    script_dir = Path(__file__).resolve().parent
    project_root = script_dir.parent.parent

    csv_path = Path(args.csv).resolve() if args.csv else auto_find_latest_csv(script_dir)
    out_path = Path(args.output).resolve() if args.output else (project_root / "code" / "navigation" / "nav_replay_route_table.h")

    if not csv_path.exists():
        raise FileNotFoundError(f"CSV not found: {csv_path}")

    points, start_heading = read_points(csv_path)

    if args.max_points <= 0:
        raise ValueError("--max-points must be > 0")

    truncated = False
    if len(points) > args.max_points:
        points = points[: args.max_points]
        truncated = True

    out_text = format_header(points, csv_path, start_heading)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(out_text, encoding="utf-8")

    print(f"[OK] CSV: {csv_path}")
    print(f"[OK] Header generated: {out_path}")
    print(f"[OK] Route points: {len(points)}")
    if start_heading is None:
        print("[OK] Start heading: N/A")
    else:
        print(f"[OK] Start heading: {start_heading:.3f} deg")
    if truncated:
        print(f"[WARN] Truncated to max points: {args.max_points}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
